[build]
publish = "public"
command = ""

[[redirects]]
from = "/"
to = "/index.html"
status = 200

[[redirects]]
from = "/app"
to = "/app/index.html"
status = 200

[[redirects]]
from = "/app/*"
to = "/app/:splat"
status = 200

[build.environment]
NODE_VERSION = "18" 