[build]
publish = "public"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
force = false
conditions = {Role = ["anonymous"]}

[[redirects]]
from = "/app/*"
to = "/app.html"
status = 200
force = true
conditions = {Role = ["user"]} 